terraform {

  required_providers {
    yandex = {
      source = "yandex-cloud/yandex"
    }
  }
}

provider "yandex" {
  zone = var.zone
}

resource "yandex_vpc_security_group" "main" {
  name        = "${var.env}-security group for ${var.projectname}"
  description = ""
  network_id  = var.network

  dynamic "ingress" {
    for_each = var.allow_ingress_ports_tcp
    content {
      protocol       = "TCP"
      description    = "Rule generated by dynamic tf"
      v4_cidr_blocks = ["0.0.0.0/0"]
      port           = ingress.value
    }
  }

  dynamic "ingress" {
    for_each = var.allow_ingress_ports_udp
    content {
      protocol       = "UDP"
      description    = "Rule generated by dynamic tf"
      v4_cidr_blocks = ["0.0.0.0/0"]
      port           = ingress.value
    }
  }

  dynamic "egress" {
    for_each = var.allow_egress_ports
    content {
      protocol       = "ANY"
      description    = "Rule generated by dynamic tf"
      v4_cidr_blocks = ["0.0.0.0/0"]
      port           = egress.value
    }
  }
}
